<a href="https://colab.research.google.com/github/Vidzhel/data-analysis/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import csv

warehouse = [
  {'name': 'Apple', 'number': 200, "price": 1, "type": "fruits"},
  {'name': 'Banana', 'number': 150, "price": 2, "type": "fruits"},
  {'name': 'Avocado', 'number': 40, "price": 5, "type": "vegetables"},
  {'name': 'Potato', 'number': 530, "price": 2, "type": "vegetables"},
]

with open('warehouse.csv', 'wt', newline='') as frecord:
  crecord = csv.DictWriter(frecord, ['name', 'number', 'price', 'type'])
  crecord.writeheader()
  crecord.writerows(warehouse)

Для аналізу, було обрано файл-приклад складу магазину

In [1]:
!curl https://diviengine.com/downloads/Divi-Engine-WooCommerce-Sample-Products.csv -o warehouse-example.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19443  100 19443    0     0  92146      0 --:--:-- --:--:-- --:--:-- 92146

In [6]:
import pandas as pd

df = pd.read_csv("warehouse-example.csv")
df.head()

,ID,Type,SKU,Name,Published,Is featured?,Visibility in catalog,Short description,Description,Date sale price starts,...,Attribute 2 name,Attribute 2 value(s),Attribute 2 visible,Attribute 2 global,Attribute 2 default,Attribute 3 name,Attribute 3 value(s),Attribute 3 visible,Attribute 3 global,Attribute 3 default
0,66,simple,NaN,Divi Engine String Bag (Big Logo),1,0,visible,This fashionable string bag is made of 100% co...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70,simple,NaN,Divi Engine String Bag (Small Logos),1,0,visible,This fashionable string bag is made of 100% co...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,74,variable,NaN,Brand Buttons,1,0,visible,"Represent your favorite CMS, eCommerce Platfor...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,75,variation,NaN,Brand Buttons - Divi,1,0,visible,NaN,Rep your love for Divi!,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,76,variation,NaN,Brand Buttons - Divi Engine,1,0,visible,NaN,Rep your love for Divi Engine!,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail()

,ID,Type,SKU,Name,Published,Is featured?,Visibility in catalog,Short description,Description,Date sale price starts,...,Attribute 2 name,Attribute 2 value(s),Attribute 2 visible,Attribute 2 global,Attribute 2 default,Attribute 3 name,Attribute 3 value(s),Attribute 3 visible,Attribute 3 global,Attribute 3 default
63,167,variation,NaN,"Divi Simplified Crop-top - Medium, White",1,0,visible,NaN,NaN,NaN,...,Color,White,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
64,168,variation,NaN,"Divi Simplified Crop-top - Medium, Yellow",1,0,visible,NaN,NaN,NaN,...,Color,Yellow,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
65,169,variation,NaN,"Divi Simplified Crop-top - Small, Blue",1,0,visible,NaN,NaN,NaN,...,Color,Blue,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
66,170,variation,NaN,"Divi Simplified Crop-top - Small, White",1,0,visible,NaN,NaN,NaN,...,Color,White,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
67,171,variation,NaN,"Divi Simplified Crop-top - Small, Yellow",1,0,visible,NaN,NaN,NaN,...,Color,Yellow,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 62 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ID                               68 non-null     int64
 1   Type                             68 non-null     object
 2   SKU                              0 non-null      float64
 3   Name                             68 non-null     object
 4   Published                        68 non-null     int64
 5   Is featured?                     68 non-null     int64
 6   Visibility in catalog            68 non-null     object
 7   Short description                16 non-null     object
 8   Description                      4 non-null      object
 9   Date sale price starts           0 non-null      float64
 10  Date sale price ends             0 non-null      float64
 11  Tax status                       68 non-null     object
 12  Tax class                        52 non-null     object
 13  In stock?                        68 non-null     object
 14  Stock                            3 non-null      float64
 15  Low stock amount                 1 non-null      float64
 16  Backorders allowed?              68 non-null     int64
 17  Sold individually?               68 non-null     int64
 18  Weight (kg)                      0 non-null      float64
 19  Length (cm)                      0 non-null      float64
 20  Width (cm)                       0 non-null      float64
 21  Height (cm)                      0 non-null      float64
 22  Allow customer reviews?          68 non-null     int64
 23  Purchase note                    0 non-null      float64
 24  Sale price                       13 non-null     float64
 25  Regular price                    55 non-null     float64
 26  Categories                       16 non-null     object
 27  Tags                             0 non-null      float64
 28  Shipping class                   0 non-null      float64
 29  Images                           38 non-null     object
 30  Download limit                   0 non-null      float64
 31  Download expiry days             0 non-null      float64
 32  Parent                           52 non-null     object
 33  Grouped products                 0 non-null      float64
 34  Upsells                          0 non-null      float64
 35  Cross-sells                      0 non-null      float64
 36  External URL                     0 non-null      float64
 37  Button text                      0 non-null      float64
 38  Position                         68 non-null     int64
 39  Attribute 1 name                 68 non-null     object
 40  Attribute 1 value(s)             68 non-null     object
 41  Attribute 1 visible              16 non-null     float64
 42  Attribute 1 global               68 non-null     int64
 43  Meta: _et_pb_post_hide_nav       16 non-null     object
 44  Meta: _et_pb_page_layout         16 non-null     object
 45  Meta: _et_pb_side_nav            16 non-null     object
 46  Meta: _et_pb_use_builder         0 non-null      float64
 47  Meta: _et_pb_first_image         0 non-null      float64
 48  Meta: _et_pb_truncate_post       0 non-null      float64
 49  Meta: _et_pb_truncate_post_date  0 non-null      float64
 50  Meta: _et_pb_old_content         0 non-null      float64
 51  Attribute 1 default              1 non-null      object
 52  Attribute 2 name                 30 non-null     object
 53  Attribute 2 value(s)             30 non-null     object
 54  Attribute 2 visible              12 non-null     float64
 55  Attribute 2 global               30 non-null     float64
 56  Attribute 2 default              12 non-null     object
 57  Attribute 3 name                 2 non-null      object
 58  Attribute 3 value(s)             2 non-null      object
 59  Attribute 3 visible              2 non-null      float64
 60  Attribute 3 global               2 non-null      float64
 61  Attribute 3 default              2 non-null      object
dtypes: float64(31), int64(8), object(23)
memory usage: 33.1+ KB

In [26]:
df[["Regular price", "Sale price"]].describe()

       Regular price  Sale price
count      55.000000   13.000000
mean       20.571818   19.528462
std        10.423781    8.262520
min         9.990000    7.990000
25%        12.990000   12.990000
50%        14.990000   12.990000
75%        29.990000   27.990000
max        44.990000   27.990000